### ISSUE TITLE
WebPack digital envelope routines::unsupported

### ISSUE THREAD

**Issue by Zego92** [PDFTron/webviewer-nextjs-sample#8]
Please make a new PR the fix next error
`Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at BulkUpdateDecorator.hashFactory (/Users/eugene/Documents/webviewer-nextjs-sample/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
    at BulkUpdateDecorator.update (/Users/eugene/Documents/webviewer-nextjs-sample/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
    at /Users/eugene/Documents/webviewer-nextjs-sample/node_modules/next/dist/compiled/webpack/bundle5.js:59321:9
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:454:9) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
`

This is already updated README.md file
[README.md](https://github.com/user-attachments/files/17189588/README.md)

**Comment by laszlo-ratesic** [comment]
+1 to the above^
